spring:
  application:
     name: safway
  data:
    mongodb:
      database: safway
      uri: mongodb+srv://dsaha0271:8598022970@dipakmongocliuster.3jprv.mongodb.net/?retryWrites=true&w=majority&appName=DIPAKMONGOCLIUSTER
